export const RENDERERS = [
  "equal_interval",
  "jenks",
  "std_deviation",
  "quantile",
];
export const COLORCODES = [
  "opacity",
  "OrRd",
  "PuBu",
  "BuPu",
  "Oranges",
  "BuGn",
  "YlOrBr",
  "YlGn",
  "Reds",
  "RdPu",
  "Greens",
  "YlGnBu",
  "Purples",
  "GnBu",
  "Greys",
  "YlOrRd",
  "PuRd",
  "Blues",
  "PuBuGn",
  "Spectral",
  "RdYlGn",
  "RdBu",
  "PiYG",
  "PRGn",
  "RdYlBu",
  "BrBG",
  "RdGy",
  "PuOr",
  "Set2",
  "Accent",
  "Set1",
  "Set3",
  "Dark2",
  "Paired",
  "Pastel2",
  "Pastel1",
];
export const NUMCLASSES = ["3", "4", "5", "6", "7", "8", "9"];
export const TOPCLASSES = ["1", "2", "3", "4", "5", "6", "7", "8", "9"];
